---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-icd-rabbitmq
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 01f5b01a-3650-4acf-aaf3-4790f7cbd422
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
